### ISSUE TITLE
Issue after updating to 1.88.0

### ISSUE THREAD

**Issue by jack-blackson** [danielperna84/hahomematic#2332]
### I agree to the following

- [x] I have read the [documentation](https://github.com/sukramj/homematicip_local#homematicip_local)
- [x] I have read the [troubleshooting documentation](https://github.com/SukramJ/aiohomematic/blob/devel/docs/homeassistant_troubleshooting.md), and tried to identify/solve the issue by myself.
- [x] I have read the [FAQs](https://github.com/sukramj/homematicip_local#frequently-asked-questions)
- [x] I am aware of the latest [release notes](https://github.com/sukramj/homematicip_local/releases)
- [x] I am aware that an integration that was installed via HACS also needs to be updated via HACS
- [x] The Backend (CCU/Homegear/...) is working as expected, devices are taught in and are controllable by its own UI.
- [x] I am running the latest version of the custom_component (and Home Assistant)

### The problem

Hello!

My Home Assistant setup today showed me that an update to 1.88 is available. I am on the latest version of home assistant, and ran the update automatically. Since then, the connection to Homematic is not possible any more. I also get these warnings in the log:

`Logger: homeassistant.setup
Quelle: setup.py:343
Erstmals aufgetreten: 15:14:23 (1 Vorkommnis)
Zuletzt protokolliert: 15:14:23

Setup failed for custom integration 'homematicip_local': Unable to import component: cannot import name 'async_register_platform_entity_service' from 'homeassistant.helpers.service' (/usr/src/homeassistant/homeassistant/helpers/service.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1003, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 37, in <module>
    from .services import async_get_loaded_config_entries, async_setup_services, async_unload_services
  File "/config/custom_components/homematicip_local/services.py", line 29, in <module>
    from homeassistant.helpers.service import (
    ...<3 lines>...
    )
ImportError: cannot import name 'async_register_platform_entity_service' from 'homeassistant.helpers.service' (/usr/src/homeassistant/homeassistant/helpers/service.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 37, in <module>
    from .services import async_get_loaded_config_entries, async_setup_services, async_unload_services
  File "/config/custom_components/homematicip_local/services.py", line 29, in <module>
    from homeassistant.helpers.service import (
    ...<3 lines>...
    )
ImportError: cannot import name 'async_register_platform_entity_service' from 'homeassistant.helpers.service' (/usr/src/homeassistant/homeassistant/helpers/service.py)`

### What version of Homematic(IP) Local for OpenCCU has the issue?

1.88

### What was the last working version of Homematic(IP) Local for OpenCCU?

_No response_

### What type of installation are you running?

Home Assistant OS

### What type of installation are you running for your Homematic backend?

CCU2

### Which version of your Homematic backend are you running?

core-2025.9.4

### What hardware are you running for your system?

Pi5

### Which config details do you use

- [ ] TLS
- [ ] callback data ([see](https://github.com/sukramj/homematicip_local#callback_host-and-callback_port))

### Which interfaces do you use?

- [x] Homematic IP
- [x] Homematic (Bidcos-RF)
- [x] Groups (Heating-Group)
- [ ] BidCos-Wired (HM-Wired)
- [ ] CuXD
- [ ] CCU-Jack

### Diagnostics information (very helpful) (no logs here)

_No response_

### The complete Protocol file (very helpful). Anything in the protocols that might be useful for us? The log (Setting/System/Protocols -> load unchanged protocol) is the best source to support trouble shooting!

```txt

```

### Additional information

_No response_

**Comment by jack-blackson** [comment]
I already restarted the Home Assistant system, and the error came up again.

**Comment by SukramJ** [comment]
Das fünfte issue #2328
